GET http://localhost:8000/discipline HTTP/1.1

### Get By ID
GET http://localhost:8000/discipline/5baf54a5-ccdc-475c-9656-ebac64814022 HTTP/1.1

### Create Discipline
POST http://localhost:8000/discipline/create HTTP/1.1
content-type: application/json

{
    "name": "Surveying"
}

### Update Discipline

PUT http://localhost:8000/discipline/update/5baf54a5-ccdc-475c-9656-ebac64814022 HTTP/1.1
content-type: application/json

{
    "name": "Engineering Surveying"
}

### Delete Discipline
DELETE http://localhost:8000/discipline/delete/5baf54a5-ccdc-475c-9656-ebac64814022 HTTP/1.1