# GET all users with pagination
GET http://localhost:8000/users?skip=0&limit=100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0NDY3NTUsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.Xodl0lPpCbBzg4OWSpZM_fuhrfCtCV1KRpbWKo9Qr4s
Accept: application/json

###
# Create a new User
POST http://localhost:8000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0MDk5NzcsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.g5pH4KqVoULwYPkaBi-EE79urP4aaQ54GvG2PEwZWjQ
Content-Type: application/json
Accept: application/json

{
    "name": "Norma User 2",
    "email": "user2@user.com",
    "password": "FFI_CONTRACTING2024!",
    "is_active": "True",
    "is_superuser": "False"
}

###
# GET my USER info
GET http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0MDk5NzcsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.g5pH4KqVoULwYPkaBi-EE79urP4aaQ54GvG2PEwZWjQ
Accept: application/json

###
# Update my email
PATCH http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0MDk5NzcsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.g5pH4KqVoULwYPkaBi-EE79urP4aaQ54GvG2PEwZWjQ
Accept: application/json
Content-Type: application/json

{
    "email": "a.abdelhay@asico.com",
    "name": "Ahmed Abdelhay"
}

###
# Update my password
PATCH http://localhost:8000/users/me/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0MDk5NzcsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.g5pH4KqVoULwYPkaBi-EE79urP4aaQ54GvG2PEwZWjQ
Content-Type: application/json
Accept: application/json

{
    "new_password": "testPassword123!",
    "current_password": "FFI_CONTRACTING2024!"
}

###
# GET user by id
GET http://localhost:8000/users/5e6309ba-5c9e-418d-898b-94d94996b9b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0NDkyNDQsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.ew0Gs1cljEHHzN3yqaWINrbUb4kPpsBoVABannxGOYw
Accept: application/json
Content-Type: application/json

###
# Patch a user by id
PATCH http://localhost:8000/users/5e6309ba-5c9e-418d-898b-94d94996b9b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0NDY3NTUsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.Xodl0lPpCbBzg4OWSpZM_fuhrfCtCV1KRpbWKo9Qr4s
Accept: application/json
Content-Type: application/json

{
    "email": "a.tes@asico.com",
    "name": "Ahmed Abdelhay"
}

###
# DELETE a user by id
DELETE http://localhost:8000/users/5e6309ba-5c9e-418d-898b-94d94996b9b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjM0NDkwMzMsInN1YiI6IjJlYzY0YmMxLTQ5YTEtNDY2NS1hZjI1LTFjN2FhYWQ5MjE1ZCJ9.AcIKbN0Zkkx3xoD8JyHgWYf-PCVNJcii41cB6Q0FWx0



###
# Sign Up
POST http://localhost:8000/users/signup
Content-Type: application/json
Accept: application/json

{
   "email": "singup@normaluser.com",
   "name": "test normal user signup",
    "password": "testPassword123!"
}
